name: "Newman Tests"
on: [push,pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run APi Tests
        run: newman run "Trello.postman_collection.json" -e Trello.postman_environment.json
